# Generated by Django 5.2.11 on 2026-02-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rename_vote_to_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='votes_vote',
        ),
    ]
