# Generated by Django 6.0.1 on 2026-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='imdb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
    ]
