# Generated by Django 4.2.27 on 2026-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_imdb_id_item_imdb_url_item_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='director',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
