# Generated by Django 5.2.11 on 2026-02-10 20:03

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def attribute_movies_to_qtrinh2(apps, schema_editor):
    """
    Attribute 18 movies added on Feb 3, 2026 around 4:43 PM UTC to qtrinh2.
    These were added via IMDB link workflow by a deleted user.
    """
    Item = apps.get_model('catalog', 'Item')
    User = apps.get_model('accounts', 'User')

    # Get qtrinh2 user
    try:
        qtrinh2 = User.objects.get(username='qtrinh2')
    except User.DoesNotExist:
        # If user doesn't exist, skip migration
        return

    # Target time: 2026-02-03 16:43:54.390407+00:00
    target_time = timezone.make_aware(timezone.datetime(2026, 2, 3, 16, 43, 54))
    start_time = target_time - timedelta(minutes=10)
    end_time = target_time + timedelta(minutes=10)

    # Update movies that were added around this time with NULL added_by
    movies = Item.objects.filter(
        created_at__gte=start_time,
        created_at__lte=end_time,
        added_by=None
    )

    updated_count = movies.update(added_by=qtrinh2)
    print(f"Attributed {updated_count} movies to qtrinh2")


def reverse_attribution(apps, schema_editor):
    """
    Reverse the attribution by setting added_by back to NULL.
    """
    Item = apps.get_model('catalog', 'Item')
    User = apps.get_model('accounts', 'User')

    try:
        qtrinh2 = User.objects.get(username='qtrinh2')
    except User.DoesNotExist:
        return

    # Target time range
    target_time = timezone.make_aware(timezone.datetime(2026, 2, 3, 16, 43, 54))
    start_time = target_time - timedelta(minutes=10)
    end_time = target_time + timedelta(minutes=10)

    # Set back to NULL for movies in this time range added by qtrinh2
    movies = Item.objects.filter(
        created_at__gte=start_time,
        created_at__lte=end_time,
        added_by=qtrinh2
    )

    updated_count = movies.update(added_by=None)
    print(f"Reversed attribution for {updated_count} movies")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_genre_field'),
        ('accounts', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.RunPython(attribute_movies_to_qtrinh2, reverse_attribution),
    ]
