# Generated by Django 5.2.11 on 2026-02-10 20:12

from django.db import migrations


def attribute_movies_to_qtrinh2(apps, schema_editor):
    """
    Attribute 64 movies to qtrinh2 (Tony Trinh).
    These were added via IMDB link workflow by a deleted user.
    """
    Item = apps.get_model('catalog', 'Item')
    User = apps.get_model('accounts', 'User')

    # Get qtrinh2 user
    try:
        qtrinh2 = User.objects.get(username='qtrinh2')
    except User.DoesNotExist:
        # If user doesn't exist, skip migration
        return

    # List of IMDB IDs to update
    imdb_ids = [
        'tt0104990', 'tt0374900', 'tt0838283', 'tt0327597', 'tt0116683',
        'tt23289160', 'tt0120685', 'tt0831387', 'tt0368226', 'tt0145487',
        'tt0105643', 'tt5215952', 'tt1706620', 'tt0368909', 'tt0427954',
        'tt0092086', 'tt0054135', 'tt0240772', 'tt0349903', 'tt0496806',
        'tt5164214', 'tt12593682', 'tt0120611', 'tt0083907', 'tt0106308',
        'tt1136608', 'tt0119654', 'tt0117509', 'tt2245084', 'tt0190641',
        'tt0286112', 'tt1099212', 'tt0087332', 'tt0087469', 'tt0089218',
        'tt0096895', 'tt0103776', 'tt0118688', 'tt0357413', 'tt0132347',
        'tt0104868', 'tt0108037', 'tt0470752', 'tt7784604', 'tt0396171',
        'tt0360486', 'tt4139124', 'tt0377092', 'tt1323594', 'tt0449059',
        'tt0383574', 'tt0067992', 'tt7589524', 'tt6292852', 'tt1663662',
        'tt0113142', 'tt2543164', 'tt2798920', 'tt2164058', 'tt15090124',
        'tt0437086', 'tt0156887', 'tt0120363', 'tt1979376'
    ]

    # Update movies
    updated_count = Item.objects.filter(imdb_id__in=imdb_ids).update(added_by=qtrinh2)
    print(f"Attributed {updated_count} movies to qtrinh2")


def reverse_attribution(apps, schema_editor):
    """
    Reverse the attribution by setting added_by back to NULL.
    """
    Item = apps.get_model('catalog', 'Item')
    User = apps.get_model('accounts', 'User')

    try:
        qtrinh2 = User.objects.get(username='qtrinh2')
    except User.DoesNotExist:
        return

    # List of IMDB IDs
    imdb_ids = [
        'tt0104990', 'tt0374900', 'tt0838283', 'tt0327597', 'tt0116683',
        'tt23289160', 'tt0120685', 'tt0831387', 'tt0368226', 'tt0145487',
        'tt0105643', 'tt5215952', 'tt1706620', 'tt0368909', 'tt0427954',
        'tt0092086', 'tt0054135', 'tt0240772', 'tt0349903', 'tt0496806',
        'tt5164214', 'tt12593682', 'tt0120611', 'tt0083907', 'tt0106308',
        'tt1136608', 'tt0119654', 'tt0117509', 'tt2245084', 'tt0190641',
        'tt0286112', 'tt1099212', 'tt0087332', 'tt0087469', 'tt0089218',
        'tt0096895', 'tt0103776', 'tt0118688', 'tt0357413', 'tt0132347',
        'tt0104868', 'tt0108037', 'tt0470752', 'tt7784604', 'tt0396171',
        'tt0360486', 'tt4139124', 'tt0377092', 'tt1323594', 'tt0449059',
        'tt0383574', 'tt0067992', 'tt7589524', 'tt6292852', 'tt1663662',
        'tt0113142', 'tt2543164', 'tt2798920', 'tt2164058', 'tt15090124',
        'tt0437086', 'tt0156887', 'tt0120363', 'tt1979376'
    ]

    # Set back to NULL
    updated_count = Item.objects.filter(
        imdb_id__in=imdb_ids,
        added_by=qtrinh2
    ).update(added_by=None)
    print(f"Reversed attribution for {updated_count} movies")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_attribute_feb3_movies_to_qtrinh2'),
        ('accounts', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.RunPython(attribute_movies_to_qtrinh2, reverse_attribution),
    ]
