# Generated by Django 5.2.11 on 2026-02-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_attribute_64_movies_to_qtrinh2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_label',
            field=models.CharField(default='movie', help_text='Singular label for items in this category (e.g. "movie", "show")', max_length=50),
        ),
    ]
