# Generated by Django 5.2.11 on 2026-02-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_catalog_managers_song_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.item'),
        ),
    ]
