# Generated by Django 5.2.11 on 2026-02-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_song_release_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.item'),
        ),
    ]
