# Generated by Django 5.2.11 on 2026-02-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_song_release_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='genre_tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
    ]
